### ISSUE TITLE
请教一下楼主ajax请求返回的数据合并问题

### ISSUE THREAD

**Issue by zwl1619** [biaochenxuying/blog-react#1]
请教一下楼主，`src/components/articles/articles.js`文件第125行，如下图所示：

![image](https://user-images.githubusercontent.com/13177997/48978012-4bcf0880-f0e0-11e8-9389-07debf6fe3dc.png)

每次下拉触发ajax请求，取回了一定数量的的数据，每取回一次都要和已经取回的数据进行一次合并操作，当一直往下拉的时候，数据会越来越多，数组越来越大，会不会性能很差呢？

**Comment by biaochenxuying** [comment]
> 请教一下楼主，`src/components/articles/articles.js`文件第125行，如下图所示：
> 
> ![image](https://user-images.githubusercontent.com/13177997/48978012-4bcf0880-f0e0-11e8-9389-07debf6fe3dc.png)
> 
> 每次下拉触发ajax请求，取回了一定数量的的数据，每取回一次都要和已经取回的数据进行一次合并操作，当一直往下拉的时候，数据会越来越多，数组越来越大，会不会性能很差呢？

性能会变差的，小数据能这么做，当然有很大数据时最好就不要了，用扩展运算符 ... 会好点。

**Comment by biaochenxuying** [comment]
> 请教一下楼主，`src/components/articles/articles.js`文件第125行，如下图所示：
> 
> ![image](https://user-images.githubusercontent.com/13177997/48978012-4bcf0880-f0e0-11e8-9389-07debf6fe3dc.png)
> 
> 每次下拉触发ajax请求，取回了一定数量的的数据，每取回一次都要和已经取回的数据进行一次合并操作，当一直往下拉的时候，数据会越来越多，数组越来越大，会不会性能很差呢？

**Comment by GodzzZZZ** [comment]
这里的 setState 用 prevState 好点吧

**Comment by GodzzZZZ** [comment]
![6ffb120239dc3d4c4f78f2998a9cafc](https://user-images.githubusercontent.com/36092926/49060049-cf0a6e80-f246-11e8-8da2-4a6278293ab5.png)
我没用官方 demo 的写法，这么写我感觉不错。code标签就不用你自己写样式了

**Comment by biaochenxuying** [comment]
查了一下，是 prevState 好；marked 的用法好多的，好用就好。

**Comment by biaochenxuying** [comment]
查了一下，是 prevState 好；marked 的用法好多的，好用就好。
